TpArticle11-01-2024/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TpArticle11_01_2024.Models;

using Entities;
using Business.Contracts;
using System.Xml.Linq;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Net;
using Business;

namespace TpArticle11_01_2024.Controllers
{
    public class ArticleController : Controller
    {
        
     

        private IArticleBusiness _articleBusiness;
        private ICommentaireBusiness _CommentaireBusiness;
        public ArticleController(IArticleBusiness articleBusiness, ICommentaireBusiness commentaireBusiness)
        {
            this._articleBusiness = articleBusiness;
            this._CommentaireBusiness = commentaireBusiness;
        }

        public ActionResult Index()
        {
           
                //// Obtenir le dernier article publié
                //var article = _articleBusiness.Articles.OrderByDescending(article => article.DateDeCreation).FirstOrDefault();

                //// Retourner la page d'accueil
                //return View(article);
            return View();

        }

       
       
        public async Task<ActionResult> Details(Article article)
        {


            
            var comments = await _CommentaireBusiness.ReadAll(article.Id);
            var Article = await _articleBusiness.Read(article.Id);
            ViewBag.ArticleId = article.Id;
            return View(new ArticleViewModel { Article = Article, Comments = comments });
            //return View( await _CommentaireBusiness.GetAllCommentaire());

        }
        
        public async Task<ActionResult> Read()
        {
            //return View(Articles);
            
             //return View(await _articleBusiness.GetAllArticle());
            return View(await _articleBusiness.ReadAll());
        }
       
        public ActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Article article)
        {
            //Articles.Add(article);
            //return RedirectToAction("Read");
            //try
            //{
            await _articleBusiness.Create(article);
            //}
            //catch (Exception ex)
            //{
            //    return (ex.);
            //}
            return RedirectToAction("Read");

        }


        public async Task<ActionResult> Update(Article article)
        {
            await _articleBusiness.Update(article);
            return View(article);

        }

        public async Task<ActionResult> UpdateValid(Article article)
        {
            //Articles.FirstOrDefault(m => m.Id == article.Id).Theme = article.Theme;
            //Articles.FirstOrDefault(m => m.Id == article.Id).DateModification = DateTime.Now;
            //Articles.FirstOrDefault(m => m.Id == article.Id).Contenu = article.Contenu;
            //return RedirectToAction("Read");
            await _articleBusiness.Update(article);
            return RedirectToAction("Read");

        }

       
        public async Task<ActionResult> Delete(int id)
        {
            //Articles.Remove(Articles.FirstOrDefault(m => m.Id == id));
            await _articleBusiness.Delete(id);
            return RedirectToAction("Read");
        }
        public async Task<IActionResult> SearchAjax(string str)
        {
            return PartialView("_displayArticlesPartial", await _articleBusiness.Search(str));
        }
        [HttpGet]
        public async Task<IActionResult> Recherche(string str = "", int pageNumber = 1)
        {
            TempData["Page"] = pageNumber;

            var arts = await _articleBusiness.ReadAll();

            if (str == "")
            {

            }
            else
            {
                arts = await _articleBusiness.Search(str);

            }


            return View(arts.OrderBy(a => a.DateCreation).ToList());
        }
        [HttpPost]
        public async Task<IActionResult> RechercheAjax(string str = "", int pageNumber = 1)
        {
            TempData["Page"] = pageNumber;

            var arts = await _articleBusiness.ReadAll();

            if (str == "")
            {

            }
            else
            {
                arts = await _articleBusiness.Search(str);

            }


            return PartialView("_SearchArticlesPartial", arts.OrderBy(a => a.DateCreation).ToList());
        }


    }
}

TpArticle11-01-2024/Controllers/CommentaireController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TpArticle11_01_2024.Models;

using Entities;

using Business.Contracts;
using Business;

namespace TpArticle11_01_2024.Controllers
{
    public class CommentaireController : Controller
    {

        private ICommentaireBusiness _CommentaireBusiness;
        private IArticleBusiness _ArticleBusiness;
        public CommentaireController(ICommentaireBusiness CommentaireBusiness,IArticleBusiness ArticleBusiness)
        {
            this._CommentaireBusiness = CommentaireBusiness;
            this._ArticleBusiness = ArticleBusiness;
        }

        public ActionResult Index()
        {
            return View();
        }


        public async Task<ActionResult> Details(int id)
        {

            //Commentaire Commentaire = Commentaires.FirstOrDefault(m => m.Id == id);

            //return View(Commentaire);
            return View(await _CommentaireBusiness.Read(id));


        }
        //public async Task<ActionResult> Read()
        //{
        //    //return View(Commentaires);

        //    return PartialView("_ReadCommentairePartial",await _CommentaireBusiness.GetAllCommentaire());

        //}

        public ActionResult Create(int ArticleId)
        {
            Commentaire MyCom = new Commentaire();
            
            MyCom.ArticleId = ArticleId;
            ViewBag.ArticleId = ArticleId;
            return View(MyCom);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Commentaire Commentaire)
        {
            //Commentaires.Add(Commentaire);
            //return RedirectToAction("Read");
            //try
            //{
            await _CommentaireBusiness.Create(Commentaire);
            //}
            //catch (Exception ex)
            //{
            //    return (ex.);
            //}

            return RedirectToAction("Details", "Article", new { id = Commentaire.ArticleId });
            //RedirectToAction("Details","Article",await _ArticleBusiness.GetArticle(Commentaire.ArticleId));

        }


        public async Task<ActionResult> Update(Commentaire Commentaire)
        {


            //await _CommentaireBusiness.Update(Commentaire);

            var com =await _CommentaireBusiness.Read(Commentaire.Id);
            return View(com);

        }

        public async Task<ActionResult> UpdateValid(Commentaire Commentaire)
        {
            //Commentaires.FirstOrDefault(m => m.Id == Commentaire.Id).Theme = Commentaire.Theme;
            //Commentaires.FirstOrDefault(m => m.Id == Commentaire.Id).DateModification = DateTime.Now;
            //Commentaires.FirstOrDefault(m => m.Id == Commentaire.Id).Contenu = Commentaire.Contenu;
            //return RedirectToAction("Read");
            await _CommentaireBusiness.Update(Commentaire);
            return RedirectToAction("Details", "Article",await _ArticleBusiness.Read(Commentaire.ArticleId));

        }


        public async Task<ActionResult> Delete(int id)
        {

           Commentaire Com = await _CommentaireBusiness.Read(id);
            Article article = await _ArticleBusiness.Read(Com.ArticleId);
                
            await _CommentaireBusiness.Delete(id);
            
            return RedirectToAction("Details", "Article", article);

        }
		[HttpPost]
		public async Task<ActionResult> Creajax(string auteur, string contenu, int articleId)
		{
			Commentaire commentaire = new Commentaire() { ArticleId = articleId, Auteur = auteur, Contenu = contenu };

			if (await _CommentaireBusiness.Create(commentaire))
			{
				TempData["Message"] = "Commentaire Ajouté en Ajax";
			}

			var coms = (await _CommentaireBusiness.ReadAll(articleId));

			return PartialView("_DisplayCommentairesPartial", coms);
		}
		[HttpPost]
        public async Task<IActionResult> DeleteFullAjax(int commentaireId)
        {
            bool res = false;
            if (await _CommentaireBusiness.Delete(commentaireId))
            {
                res = true;
                TempData["Message"] = "Suppr. Ajax et delete row";
            }
            else
            {

                TempData["Message"] = "";

            }

            return Json(res);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteAspAjax(int commentaireId)
        {
            var com = await _CommentaireBusiness.Read(commentaireId);
            int articleId = com.ArticleId;

            if (await _CommentaireBusiness.Delete(commentaireId))
            {
                TempData["Message"] = "Suppr. Ajax et MAJ vue partielle";
            }
            else
            {
                TempData["Message"] = "";
            }

            var coms = (await _CommentaireBusiness.ReadAll(articleId));

            return PartialView("_DisplayCommentairesPartial", coms);
        }
		

	}
}

TpArticle11-01-2024/Views/Shared/_DisplayArticlesPartial.cshtml
@model List<Article>

<table class="table table-striped table-sm table-bordered text-center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Theme</th>
            <th>Auteur</th>
            <th>Contenu</th>
            <th>DateCre</th>
            <th>DateMod</th>
        </tr>
    </thead>
    <tbody id="contentMessage">
        @foreach (var article in Model)
        {
            <tr>
                <td>@article.Id</td>
                <td>@article.Theme</td>
                <td>@article.Auteur</td>
                <td>@article.Contenu</td>
                <td>@article.DateCreation</td>
                <td>@article.DateModification</td>
                
                <td>
                    <a asp-action="Read" asp-route-id="@article.Id">Detail</a>
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@article.Id">Supprimer</a>
                </td>
            </tr>
        }
    </tbody>
</table>

TpArticle11-01-2024/Views/Shared/_DisplayCommentairesPartial.cshtml
@model ArticleViewModel
@{
    ViewData["Title"] = "Read";
}



<p>
    <a asp-action="Create" asp-route-ArticleId="@Model.Article.Id" asp-controller="Commentaire">Créer un nouveau</a>
</p>
<form>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Auteur</th>
                <th>DateCreation</th>
                <th>DateModif</th>
                <th>Contenu</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.Comments)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Auteur)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateCreation)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateModification)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Contenu)
                    </td>
                    <td>
                        <button asp-action="Update" asp-route-Id="@item.Id" asp-route-ArticleId="@Model.Article.Id" asp-controller="Commentaire">Update</button>

                        <button asp-action="Delete" asp-route-Id="@item.Id" asp-controller="Commentaire">Delete</button>
                        <button asp-action="Details" asp-route-Id="@item.Id" asp-controller="Commentaire">Details</button>
                    </td>
                    <td>
                        <button onclick="SupprimerFullAjax(this)">DelFullAjax</button>
                    </td>

                    <td>
                        <button onclick="SupprimerAspAjax(@item.Id)">DelAspAjax</button>
                    </td>
                    
                </tr>
            }
        </tbody>
    </table>
</form>
<script>

    function SupprimerFullAjax(commentaire) {

        var row = commentaire.parentNode.parentNode;
        var commentaireId = row.cells[0].innerText;

        $.post('/Commentaire/DeleteFullAjax', { commentaireId: commentaireId }, function (isDelete) {
            if (isDelete == true)
                row.parentNode.removeChild(row);
        });
    }

    function SupprimerAspAjax(commentaireId) {

        $.post('/Commentaire/DeleteAspAjax', { commentaireId: commentaireId }, function (data) {
            $('#divContentMessages').html(data);
        });
    }


</script>
<a asp-action="Read" asp-controller="Article">Retour</a>

TpArticle11-01-2024/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TpArticle11_01_2024</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TpArticle11_01_2024.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TpArticle11_01_2024</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Read">Article</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Commentaire" asp-action="Read">Commentaire</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Recherche">Recherche</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TpArticle11_01_2024 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TpArticle11-01-2024/Views/Shared/_ReadArticlePartial.cshtml
@model ArticleViewModel

@{
    ViewData["Title"] = "Details";
}



<form>


    <label>Id :</label>@Model.Article.Id<br />
    <label>Thème :</label>@Model.Article.Theme<br />
    <label>Auteur :</label>@Model.Article.Auteur<br />
    <label>Date de creation :</label>@Model.Article.DateCreation<br />
    <label>Date de modification :</label>@Model.Article.DateModification<br />
    <label>Contenu :</label>@Model.Article.Contenu<br />

    <br />
    <button asp-action="Update" asp-route-Id="@Model.Article.Id">Update</button>

    <button asp-action="Delete" asp-route-Id="@Model.Article.Id">Delete</button>



</form>

<partial name="_DisplayCommentairesPartial" />

<br /><br />
<partial name="_formCommentairePartial" model="new Commentaire(){ArticleId = Model.Article.Id}" />

<br />

<form id="formAdd">
	<input id="ArticleId" value="@Model.Article.Id" type="hidden" />
	<label>Auteur :</label>
	<input id="AuteurAjax" type="text" />
	<label>Contenu :</label>
	<input id="ContenuAjax" type="text" />

	<button>Ajouter Ajax</button>

</form>


<script>


	$(function () {
		$('#formAdd').submit(function (e) {
			$.post('/Commentaire/CreAjax', { articleId: $('#ArticleId').val(), auteur: $('#AuteurAjax').val(), contenu: $('#ContenuAjax').val() }, function (data) {

				//alert(data);
				$('#divContentMessages').html(data);
			});

			e.preventDefault();
		});

	});


</script>

TpArticle11-01-2024/Views/Shared/_ReadCommentairePartial.cshtml
@model List<Commentaire>

@{
    ViewData["Title"] = "Read";
}

<h1>Commentaires :</h1>

<p>
    <a asp-action="Create" asp-route-Id="">Créer un nouveau</a>
</p>
<form>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Auteur</th>
                <th>DateCreation</th>
                <th>DateModif</th>
                <th>Contenu</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Auteur)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateCreation)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateModification)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Contenu)
                    </td>
                    <td>
                        <button asp-action="Update" asp-route-Id="@item.Id">Update</button>

                        <button asp-action="Delete" asp-route-Id="@item.Id">Delete</button>
                        <button asp-action="Details" asp-route-Id="@item.Id">Details</button>

                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>

TpArticle11-01-2024/Views/Shared/_SearchArticlesPartial.cshtml
@model List<Article>

@{
	int pageSize = 10; // Nombre d'éléments par page
	int pageNumber = (int)TempData["Page"]; // Numéro de page actuel
	int totalPages = (Model.Count + pageSize - 1) / pageSize; // Nombre total de pages
}


<div>

	@if (pageNumber > 1)
	{
		<a href="@Url.Action("Recherche", "Article", new { pageNumber = pageNumber - 1 })">Page précédente</a>
	}
	Page @pageNumber de @totalPages
	@if (pageNumber < totalPages)
	{
		<a href="@Url.Action("Recherche", "Article", new { pageNumber = pageNumber + 1 })">Page suivante</a>
	}
</div>




<table class="table table-striped table-sm table-bordered text-center">
	<thead>
		<tr>
			<th>Id</th>
			<th>Theme</th>
			<th>Auteur</th>
			<th>Contenu</th>
			<th>DateCre</th>
			<th>DateMod</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model.Skip((pageNumber - 1) * pageSize).Take(pageSize))
		{

			<tr>
				<td>@item.Id</td>
				<td><strong>@item.Theme</strong></td>
				<td>@item.Auteur</td>
				<td>@item.Contenu</td>
				<td>@item.DateCreation</td>
				<td>@item.DateModification</td>
				<td>
					<a asp-action="Read" asp-route-id="@item.Id">Detail</a>
				</td>
			</tr>


			@foreach (var com in item.Commentaires)
			{

				@* <tbody> *@
				<tr>
					<td> </td>
					<td>@com.Id</td>
					<td>@com.Auteur</td>
					<td>@com.Contenu</td>
					<td>@com.DateCreation</td>
					<td>@com.DateModification</td>
				</tr>
				@* </tbody> *@

			}
		}
	</tbody>
</table>
		

TpArticle11-01-2024/Views/Shared/_formCommentairePartial.cshtml
@model Commentaire

<form asp-controller="Commentaire" asp-action="Create">
	<input asp-for="ArticleId" type="hidden" />

	<label>Auteur :</label>
	<input asp-for="Auteur" type="text" placeholder="@Model.Auteur" />
	<span asp-validation-for="Auteur"></span>
	<label>Contenu :</label>
	<input asp-for="Contenu" type="text" placeholder="@Model.Contenu" />


	<button>Ajouter .Net</button>

</form>